/**
 * China TC260 AI Safety Governance Framework Comprehensive Guide
 * The definitive resource for understanding China's AI safety governance approach
 */

import { motion } from "framer-motion";
import {
  Shield, CheckCircle2, AlertTriangle, FileText, Building2, Globe,
  BookOpen, ArrowRight, ExternalLink, Layers, Network, Eye,
  Users, Lock, AlertCircle, Cog, GraduationCap, BarChart3,
  ClipboardCheck, Workflow, Scale, Bell, Tag, Database, Zap,
  Award, Radio, MessageSquare, FileWarning, Handshake
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Link } from "wouter";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function TC260Guide() {
  const frameworkEvolution = [
    {
      version: "1.0",
      date: "September 2023",
      title: "Initial Framework",
      description: "First comprehensive AI safety governance framework published by TC260",
      keyFeatures: [
        "Basic risk classification system",
        "Initial content moderation requirements",
        "Foundational governance principles"
      ]
    },
    {
      version: "2.0",
      date: "September 2025",
      title: "Enhanced Framework",
      description: "Major update with expanded scope and detailed implementation guidance",
      keyFeatures: [
        "Enhanced content labeling requirements",
        "Emergency response guidelines",
        "Incident classification system",
        "Global cooperation mechanisms"
      ]
    }
  ];

  const contentLabelingRequirements = [
    {
      category: "AI-Generated Content",
      icon: Tag,
      color: "blue",
      description: "All content generated by AI systems must be clearly labeled",
      requirements: [
        "Visible watermarks on AI-generated images and videos",
        "Text indicators for AI-generated written content",
        "Audio watermarks for AI-generated speech and music",
        "Metadata embedding for traceability",
        "Real-time labeling for streaming content"
      ],
      implementation: "Labels must be persistent, tamper-resistant, and machine-readable"
    },
    {
      category: "Deepfake Detection",
      icon: Eye,
      color: "purple",
      description: "Systems must detect and flag synthetic media content",
      requirements: [
        "Automated deepfake detection capabilities",
        "Confidence scoring for synthetic content",
        "User notification mechanisms",
        "Reporting channels for synthetic media",
        "Archive of detected synthetic content"
      ],
      implementation: "Detection systems must achieve minimum accuracy thresholds"
    },
    {
      category: "Source Attribution",
      icon: Database,
      color: "green",
      description: "AI-assisted content must disclose AI involvement",
      requirements: [
        "Disclosure of AI assistance level",
        "Training data source attribution (where applicable)",
        "Model version and provider identification",
        "Modification history tracking",
        "Human oversight disclosure"
      ],
      implementation: "Attribution must be accessible to end users and regulators"
    },
    {
      category: "Platform Responsibilities",
      icon: Building2,
      color: "orange",
      description: "Platforms distributing AI content have specific obligations",
      requirements: [
        "Content verification before distribution",
        "Label preservation across platform transfers",
        "User reporting mechanisms",
        "Content takedown procedures",
        "Regular compliance audits"
      ],
      implementation: "Platforms must implement technical and organizational measures"
    }
  ];

  const emergencyResponseGuidelines = [
    {
      level: "Level 1",
      severity: "Critical",
      color: "red",
      title: "Critical AI Safety Incident",
      description: "Incidents causing or likely to cause widespread harm to public safety, national security, or social stability",
      examples: [
        "AI system causing physical harm at scale",
        "Critical infrastructure compromise via AI",
        "Widespread dissemination of harmful AI-generated content",
        "AI system manipulation affecting public order"
      ],
      responseTime: "Immediate (within 1 hour)",
      actions: [
        "Immediate system shutdown",
        "Notify national authorities",
        "Public warning issuance",
        "Evidence preservation",
        "Inter-agency coordination"
      ]
    },
    {
      level: "Level 2",
      severity: "High",
      color: "orange",
      title: "Significant AI Safety Incident",
      description: "Incidents with significant impact on individuals, organizations, or specific sectors",
      examples: [
        "Large-scale data breach via AI system",
        "AI-enabled fraud affecting multiple victims",
        "Significant bias incidents in public services",
        "AI system failures in critical applications"
      ],
      responseTime: "Within 4 hours",
      actions: [
        "System isolation",
        "Sector regulator notification",
        "Affected party notification",
        "Root cause investigation",
        "Mitigation plan development"
      ]
    },
    {
      level: "Level 3",
      severity: "Medium",
      color: "yellow",
      title: "Moderate AI Safety Incident",
      description: "Incidents with limited scope but requiring formal response and reporting",
      examples: [
        "Localized AI system malfunction",
        "Individual privacy violations",
        "Contained bias incidents",
        "Minor security vulnerabilities"
      ],
      responseTime: "Within 24 hours",
      actions: [
        "Incident documentation",
        "Internal investigation",
        "Corrective measures",
        "Regulatory reporting (if required)",
        "Lessons learned capture"
      ]
    },
    {
      level: "Level 4",
      severity: "Low",
      color: "green",
      title: "Minor AI Safety Incident",
      description: "Incidents with minimal impact, handled through normal operational procedures",
      examples: [
        "Minor accuracy issues",
        "User experience problems",
        "Documentation gaps",
        "Minor compliance deviations"
      ],
      responseTime: "Within 72 hours",
      actions: [
        "Standard incident logging",
        "Operational review",
        "Process adjustment",
        "Internal reporting",
        "Preventive measures"
      ]
    }
  ];

  const incidentClassification = [
    {
      category: "Safety Incidents",
      icon: Shield,
      description: "Incidents affecting physical or psychological safety",
      subcategories: [
        "Physical harm caused by AI systems",
        "Psychological harm from AI content",
        "Safety-critical system failures",
        "Autonomous system malfunctions"
      ]
    },
    {
      category: "Security Incidents",
      icon: Lock,
      description: "Incidents affecting system or data security",
      subcategories: [
        "AI model theft or leakage",
        "Adversarial attacks on AI systems",
        "Data poisoning incidents",
        "Unauthorized AI system access"
      ]
    },
    {
      category: "Ethics Incidents",
      icon: Scale,
      description: "Incidents involving ethical violations",
      subcategories: [
        "Discrimination and bias manifestation",
        "Privacy violations",
        "Lack of transparency",
        "Accountability gaps"
      ]
    },
    {
      category: "Compliance Incidents",
      icon: FileWarning,
      description: "Incidents involving regulatory non-compliance",
      subcategories: [
        "Content labeling violations",
        "Registration requirement violations",
        "Reporting failures",
        "Cross-border data violations"
      ]
    }
  ];

  const frameworkComparison = [
    {
      aspect: "Legal Status",
      tc260: "Binding regulatory framework with enforcement mechanisms",
      euAiAct: "Binding regulation with significant penalties",
      nistRmf: "Voluntary guidance framework"
    },
    {
      aspect: "Risk Approach",
      tc260: "Risk classification with content-specific requirements",
      euAiAct: "Four-tier risk classification system",
      nistRmf: "Flexible, continuous risk assessment"
    },
    {
      aspect: "Content Labeling",
      tc260: "Mandatory labeling for all AI-generated content",
      euAiAct: "Required for specific AI interactions and deepfakes",
      nistRmf: "Recommended as transparency measure"
    },
    {
      aspect: "Registration",
      tc260: "Mandatory algorithm registration with authorities",
      euAiAct: "EU database registration for high-risk AI",
      nistRmf: "No registration requirement"
    },
    {
      aspect: "Real-time Oversight",
      tc260: "Active monitoring by regulators",
      euAiAct: "Market surveillance by authorities",
      nistRmf: "Self-assessment and voluntary disclosure"
    },
    {
      aspect: "Content Moderation",
      tc260: "Detailed content moderation requirements",
      euAiAct: "General transparency obligations",
      nistRmf: "Addressed through trustworthy characteristics"
    },
    {
      aspect: "Cross-border",
      tc260: "Data localization and cross-border transfer controls",
      euAiAct: "GDPR-aligned data transfer mechanisms",
      nistRmf: "No specific cross-border provisions"
    },
    {
      aspect: "Emergency Response",
      tc260: "Detailed incident classification and response",
      euAiAct: "Serious incident reporting requirements",
      nistRmf: "General incident response guidance"
    }
  ];

  const globalCooperationMechanisms = [
    {
      title: "Bilateral Agreements",
      icon: Handshake,
      description: "Framework for AI safety cooperation with individual countries",
      elements: [
        "Information sharing protocols",
        "Joint incident investigation procedures",
        "Mutual recognition discussions",
        "Technical standards harmonization"
      ]
    },
    {
      title: "Multilateral Forums",
      icon: Globe,
      description: "Participation in international AI governance bodies",
      elements: [
        "UN AI governance discussions",
        "G20 AI principles alignment",
        "ISO/IEC standards development",
        "Regional cooperation frameworks"
      ]
    },
    {
      title: "Industry Cooperation",
      icon: Building2,
      description: "Engagement with international technology companies",
      elements: [
        "Compliance guidance for foreign companies",
        "Technical exchange programs",
        "Joint research initiatives",
        "Best practice sharing"
      ]
    },
    {
      title: "Academic Exchange",
      icon: GraduationCap,
      description: "International research collaboration on AI safety",
      elements: [
        "Joint research programs",
        "Academic conference participation",
        "Publication and knowledge sharing",
        "Talent exchange programs"
      ]
    }
  ];

  const csoaiCoverage = [
    {
      title: "Content Labeling Compliance",
      description: "Tools and templates for implementing TC260's comprehensive content labeling requirements across AI-generated outputs.",
      link: "/workbench"
    },
    {
      title: "Incident Response Framework",
      description: "Pre-built incident classification and response workflows aligned with TC260's four-level emergency response system.",
      link: "/compliance"
    },
    {
      title: "Risk Assessment Tools",
      description: "Assessment frameworks that map to TC260's risk classification approach alongside EU and US standards.",
      link: "/risk-assessment"
    },
    {
      title: "Multi-Framework Compliance",
      description: "Unified compliance tracking across TC260, EU AI Act, NIST AI RMF, and ISO 42001 requirements.",
      link: "/compliance"
    },
    {
      title: "Documentation Management",
      description: "Comprehensive documentation system meeting TC260's reporting and record-keeping requirements.",
      link: "/ai-systems"
    },
    {
      title: "Training Programs",
      description: "TC260 framework training modules alongside other international AI governance standards.",
      link: "/courses"
    }
  ];

  const algorithmRegistration = {
    description: "China requires registration of AI algorithms that influence public opinion or have significant social impact.",
    requirements: [
      {
        title: "Registration Scope",
        items: [
          "Recommendation algorithms",
          "Content generation algorithms",
          "Synthesis/deepfake algorithms",
          "Decision-making algorithms affecting rights"
        ]
      },
      {
        title: "Required Information",
        items: [
          "Algorithm name and type",
          "Application scenarios",
          "Technical characteristics",
          "Security assessment results",
          "Service provider information"
        ]
      },
      {
        title: "Ongoing Obligations",
        items: [
          "Regular security assessments",
          "Algorithm updates notification",
          "Annual compliance reports",
          "User complaint handling"
        ]
      }
    ]
  };

  const faqs = [
    {
      question: "What is TC260 and what is its role in China's AI governance?",
      answer: "TC260 (National Information Security Standardization Technical Committee) is China's primary body for developing information security and AI safety standards. It operates under the Standardization Administration of China and works closely with the Cyberspace Administration of China (CAC). TC260 develops the technical standards that implement China's AI regulations, including the AI Safety Governance Framework."
    },
    {
      question: "How does the AI Safety Governance Framework 2.0 differ from version 1.0?",
      answer: "Version 2.0 (September 2025) significantly expands on the initial framework with: enhanced content labeling requirements across all media types, detailed emergency response guidelines with a four-level classification system, comprehensive incident reporting procedures, expanded global cooperation mechanisms, and more specific implementation guidance for various industry sectors."
    },
    {
      question: "What content labeling requirements apply to AI-generated content?",
      answer: "All AI-generated content must be labeled through: visible watermarks on images and videos, text indicators for written content, audio watermarks for voice/music, and persistent metadata for traceability. Labels must be tamper-resistant and machine-readable. Platforms distributing AI content must preserve these labels and implement verification systems."
    },
    {
      question: "What is China's algorithm registration requirement?",
      answer: "Organizations operating in China must register AI algorithms that influence public opinion or have significant social impact with the Cyberspace Administration of China. This includes recommendation algorithms, content generation systems, and deepfake technology. Registration requires detailed technical documentation, security assessments, and ongoing compliance reporting."
    },
    {
      question: "How do TC260 requirements compare to the EU AI Act?",
      answer: "Both frameworks take a risk-based approach but differ in implementation: TC260 has mandatory content labeling for all AI content (EU only for specific cases), TC260 requires algorithm registration (EU has database for high-risk AI), TC260 emphasizes active regulatory oversight (EU relies more on self-assessment), and TC260 includes data localization requirements not present in EU law."
    },
    {
      question: "What are the emergency response requirements under TC260?",
      answer: "TC260 Framework 2.0 establishes a four-level incident response system: Level 1 (Critical) requires immediate response within 1 hour with national authority notification, Level 2 (High) within 4 hours with sector regulator notification, Level 3 (Medium) within 24 hours with formal documentation, and Level 4 (Low) within 72 hours through standard procedures."
    },
    {
      question: "Does TC260 apply to foreign companies?",
      answer: "Yes, TC260 requirements apply to any organization providing AI services to users in China, regardless of where the organization is headquartered. Foreign companies must comply with algorithm registration, content labeling, data localization, and other requirements if their services are accessible in China. The framework includes provisions for cross-border data transfers."
    },
    {
      question: "How does TC260 address generative AI specifically?",
      answer: "Generative AI faces specific requirements under TC260 including: mandatory registration of generation algorithms, comprehensive content labeling for all outputs, training data documentation and compliance, content filtering and moderation systems, user verification for certain applications, and special provisions for deepfake and synthetic media."
    },
    {
      question: "What are the penalties for non-compliance with TC260 requirements?",
      answer: "Non-compliance can result in: service suspension or termination in China, financial penalties based on violation severity, mandatory corrective measures, public disclosure of violations, restrictions on new service launches, and potential impact on other business operations in China. The severity depends on the incident classification level."
    },
    {
      question: "How can organizations comply with both TC260 and EU AI Act?",
      answer: "Organizations can achieve dual compliance by: implementing comprehensive content labeling meeting both standards, establishing incident response systems covering both frameworks' requirements, maintaining documentation satisfying both reporting obligations, conducting risk assessments aligned with both approaches, and using unified governance structures that address overlapping requirements."
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <section className="relative py-20 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-red-600/20 via-orange-500/10 to-yellow-500/10" />
        <div className="absolute inset-0 bg-[url('/grid.svg')] bg-center opacity-10" />
        <div className="container max-w-7xl mx-auto px-6 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center space-y-6 max-w-4xl mx-auto"
          >
            <div className="flex items-center justify-center gap-2 mb-4">
              <Badge variant="outline" className="text-sm px-4 py-2 bg-red-500/10 border-red-500/30">
                <Globe className="h-4 w-4 mr-2" />
                China TC260 | AI Safety Framework 2.0 | September 2025
              </Badge>
            </div>
            <h1 className="text-5xl md:text-6xl font-bold tracking-tight">
              The Complete Guide to
              <span className="bg-gradient-to-r from-red-600 to-orange-600 bg-clip-text text-transparent"> China TC260</span>
            </h1>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
              China's comprehensive AI Safety Governance Framework. Understand content labeling requirements,
              emergency response guidelines, incident classification, and how it compares to EU and US frameworks.
              Essential knowledge for global AI operations.
            </p>
            <div className="flex flex-wrap gap-4 justify-center pt-4">
              <Link href="/courses">
                <Button size="lg" className="bg-gradient-to-r from-red-600 to-orange-600 hover:from-red-700 hover:to-orange-700">
                  <GraduationCap className="mr-2 h-5 w-5" />
                  Start TC260 Training
                </Button>
              </Link>
              <Link href="/compliance">
                <Button size="lg" variant="outline">
                  <BarChart3 className="mr-2 h-5 w-5" />
                  Check Multi-Framework Compliance
                </Button>
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Quick Stats */}
      <section className="border-y bg-muted/30">
        <div className="container max-w-7xl mx-auto px-6 py-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            <div>
              <div className="text-3xl font-bold text-red-600">v2.0</div>
              <div className="text-sm text-muted-foreground">Current Version</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-orange-600">Sept 2025</div>
              <div className="text-sm text-muted-foreground">Latest Update</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-yellow-600">4 Levels</div>
              <div className="text-sm text-muted-foreground">Incident Classification</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-green-600">Global</div>
              <div className="text-sm text-muted-foreground">Cooperation Framework</div>
            </div>
          </div>
        </div>
      </section>

      {/* Framework Evolution */}
      <section className="py-20 px-6">
        <div className="container max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="grid lg:grid-cols-2 gap-12 items-start"
          >
            <div className="space-y-6">
              <Badge variant="secondary" className="text-sm">Understanding the Framework</Badge>
              <h2 className="text-4xl font-bold">AI Safety Governance Framework</h2>
              <div className="space-y-4 text-lg text-muted-foreground">
                <p>
                  The <strong className="text-foreground">TC260 AI Safety Governance Framework</strong> is China's
                  comprehensive regulatory approach to artificial intelligence. Developed by the National Information
                  Security Standardization Technical Committee (TC260), it establishes binding requirements for
                  organizations deploying AI systems in China.
                </p>
                <p>
                  Version 2.0, released in September 2025, significantly expanded the framework with enhanced
                  content labeling requirements, detailed emergency response guidelines, and mechanisms for
                  international cooperation on AI safety.
                </p>
                <p>
                  The framework applies to all organizations operating AI systems that serve Chinese users,
                  regardless of where the organization is headquartered, making it essential knowledge for
                  global AI governance strategies.
                </p>
              </div>
            </div>
            <div className="space-y-6">
              {frameworkEvolution.map((version, idx) => (
                <motion.div
                  key={version.version}
                  initial={{ opacity: 0, x: 20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.1 }}
                >
                  <Card className={`p-6 ${idx === frameworkEvolution.length - 1 ? 'border-red-500/30 bg-red-500/5' : ''}`}>
                    <div className="flex items-center gap-3 mb-3">
                      <Badge variant={idx === frameworkEvolution.length - 1 ? 'default' : 'secondary'} className={idx === frameworkEvolution.length - 1 ? 'bg-red-500' : ''}>
                        Version {version.version}
                      </Badge>
                      <span className="text-sm text-muted-foreground">{version.date}</span>
                    </div>
                    <h3 className="text-xl font-bold mb-2">{version.title}</h3>
                    <p className="text-sm text-muted-foreground mb-4">{version.description}</p>
                    <div className="space-y-2">
                      {version.keyFeatures.map((feature, fIdx) => (
                        <div key={fIdx} className="flex items-center gap-2 text-sm">
                          <CheckCircle2 className="h-4 w-4 text-green-600 flex-shrink-0" />
                          {feature}
                        </div>
                      ))}
                    </div>
                  </Card>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </div>
      </section>

      {/* Content Labeling Requirements */}
      <section className="py-20 px-6 bg-muted/30">
        <div className="container max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <Badge variant="secondary" className="text-sm mb-4">Core Requirement</Badge>
            <h2 className="text-4xl font-bold mb-4">Content Labeling Requirements</h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              TC260 mandates comprehensive labeling for all AI-generated content to ensure transparency and traceability.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-6">
            {contentLabelingRequirements.map((req, idx) => {
              const colorClasses = {
                blue: "bg-blue-500/10 border-blue-500/20",
                purple: "bg-purple-500/10 border-purple-500/20",
                green: "bg-green-500/10 border-green-500/20",
                orange: "bg-orange-500/10 border-orange-500/20"
              }[req.color];

              const iconColorClass = {
                blue: "text-blue-600",
                purple: "text-purple-600",
                green: "text-green-600",
                orange: "text-orange-600"
              }[req.color];

              return (
                <motion.div
                  key={req.category}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.1 }}
                >
                  <Card className={`h-full p-6 ${colorClasses}`}>
                    <div className="flex items-center gap-3 mb-4">
                      <div className="p-3 rounded-xl bg-white dark:bg-gray-900 shadow-sm">
                        <req.icon className={`h-6 w-6 ${iconColorClass}`} />
                      </div>
                      <h3 className="text-xl font-bold">{req.category}</h3>
                    </div>
                    <p className="text-sm text-muted-foreground mb-4">{req.description}</p>
                    <div className="space-y-2 mb-4">
                      {req.requirements.map((item, itemIdx) => (
                        <div key={itemIdx} className="flex items-start gap-2 text-sm">
                          <CheckCircle2 className="h-4 w-4 text-green-600 mt-0.5 flex-shrink-0" />
                          {item}
                        </div>
                      ))}
                    </div>
                    <div className="pt-4 border-t">
                      <p className="text-xs text-muted-foreground">
                        <strong>Implementation:</strong> {req.implementation}
                      </p>
                    </div>
                  </Card>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Emergency Response Guidelines */}
      <section className="py-20 px-6">
        <div className="container max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <Badge variant="secondary" className="text-sm mb-4">Incident Management</Badge>
            <h2 className="text-4xl font-bold mb-4">Emergency Response Guidelines</h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              TC260 Framework 2.0 introduces a comprehensive four-level emergency response system for AI safety incidents.
            </p>
          </motion.div>

          <div className="space-y-6">
            {emergencyResponseGuidelines.map((level, idx) => {
              const colorClasses = {
                red: "bg-red-500/10 border-red-500/30",
                orange: "bg-orange-500/10 border-orange-500/30",
                yellow: "bg-yellow-500/10 border-yellow-500/30",
                green: "bg-green-500/10 border-green-500/30"
              }[level.color];

              const badgeClasses = {
                red: "bg-red-500 text-white",
                orange: "bg-orange-500 text-white",
                yellow: "bg-yellow-500 text-black",
                green: "bg-green-500 text-white"
              }[level.color];

              return (
                <motion.div
                  key={level.level}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.1 }}
                >
                  <Card className={`p-6 ${colorClasses} border-2`}>
                    <div className="grid lg:grid-cols-3 gap-6">
                      <div className="lg:col-span-2">
                        <div className="flex items-center gap-3 mb-4">
                          <Badge className={badgeClasses}>{level.level}</Badge>
                          <Badge variant="outline">{level.severity}</Badge>
                          <Badge variant="secondary">Response: {level.responseTime}</Badge>
                        </div>
                        <h3 className="text-2xl font-bold mb-2">{level.title}</h3>
                        <p className="text-muted-foreground mb-4">{level.description}</p>
                        <div>
                          <h4 className="font-semibold text-sm mb-2">Example Incidents:</h4>
                          <div className="grid md:grid-cols-2 gap-2">
                            {level.examples.map((example, exIdx) => (
                              <div key={exIdx} className="flex items-center gap-2 text-sm">
                                <AlertCircle className="h-3.5 w-3.5 text-muted-foreground flex-shrink-0" />
                                {example}
                              </div>
                            ))}
                          </div>
                        </div>
                      </div>
                      <div className="bg-white/50 dark:bg-gray-900/50 rounded-lg p-4">
                        <h4 className="font-semibold text-sm mb-3">Required Actions:</h4>
                        <div className="space-y-2">
                          {level.actions.map((action, actIdx) => (
                            <div key={actIdx} className="flex items-start gap-2 text-sm">
                              <div className="w-5 h-5 rounded-full bg-background flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">
                                {actIdx + 1}
                              </div>
                              {action}
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </Card>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Incident Classification */}
      <section className="py-20 px-6 bg-muted/30">
        <div className="container max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <Badge variant="secondary" className="text-sm mb-4">Incident Taxonomy</Badge>
            <h2 className="text-4xl font-bold mb-4">Incident Classification System</h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              TC260 categorizes AI safety incidents into four main categories for appropriate handling.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-6">
            {incidentClassification.map((category, idx) => (
              <motion.div
                key={category.category}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.1 }}
              >
                <Card className="h-full p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="p-3 rounded-xl bg-red-500/10">
                      <category.icon className="h-6 w-6 text-red-600" />
                    </div>
                    <div>
                      <h3 className="font-bold text-lg">{category.category}</h3>
                      <p className="text-sm text-muted-foreground">{category.description}</p>
                    </div>
                  </div>
                  <div className="space-y-2">
                    {category.subcategories.map((sub, subIdx) => (
                      <div key={subIdx} className="flex items-center gap-2 text-sm">
                        <div className="w-1.5 h-1.5 rounded-full bg-red-500" />
                        {sub}
                      </div>
                    ))}
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Framework Comparison */}
      <section className="py-20 px-6">
        <div className="container max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <Badge variant="secondary" className="text-sm mb-4">Global Context</Badge>
            <h2 className="text-4xl font-bold mb-4">How It Compares to EU/US Frameworks</h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              Understanding the similarities and differences between TC260, EU AI Act, and NIST AI RMF.
            </p>
          </motion.div>

          <Card className="overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="bg-muted/50">
                    <th className="text-left p-4 font-semibold">Aspect</th>
                    <th className="text-left p-4 font-semibold">
                      <div className="flex items-center gap-2">
                        <div className="w-3 h-3 rounded-full bg-red-500" />
                        TC260 Framework
                      </div>
                    </th>
                    <th className="text-left p-4 font-semibold">
                      <div className="flex items-center gap-2">
                        <div className="w-3 h-3 rounded-full bg-blue-500" />
                        EU AI Act
                      </div>
                    </th>
                    <th className="text-left p-4 font-semibold">
                      <div className="flex items-center gap-2">
                        <div className="w-3 h-3 rounded-full bg-purple-500" />
                        NIST AI RMF
                      </div>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {frameworkComparison.map((row, idx) => (
                    <tr key={row.aspect} className={idx % 2 === 0 ? 'bg-background' : 'bg-muted/20'}>
                      <td className="p-4 font-medium">{row.aspect}</td>
                      <td className="p-4 text-sm">{row.tc260}</td>
                      <td className="p-4 text-sm">{row.euAiAct}</td>
                      <td className="p-4 text-sm">{row.nistRmf}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>
        </div>
      </section>

      {/* Algorithm Registration */}
      <section className="py-20 px-6 bg-gradient-to-br from-red-500/10 via-orange-500/5 to-yellow-500/10">
        <div className="container max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
          >
            <Card className="p-8 border-red-500/30 bg-white/50 dark:bg-gray-950/50">
              <div className="flex items-start gap-4 mb-6">
                <div className="p-3 rounded-xl bg-red-500/20">
                  <Database className="h-8 w-8 text-red-600" />
                </div>
                <div>
                  <Badge variant="outline" className="mb-2 border-red-500/30 text-red-600">
                    Mandatory Requirement
                  </Badge>
                  <h2 className="text-3xl font-bold">Algorithm Registration</h2>
                  <p className="text-muted-foreground mt-2">{algorithmRegistration.description}</p>
                </div>
              </div>

              <div className="grid md:grid-cols-3 gap-6">
                {algorithmRegistration.requirements.map((req, idx) => (
                  <Card key={idx} className="p-4 bg-red-500/5">
                    <h4 className="font-semibold text-red-700 dark:text-red-400 mb-3">{req.title}</h4>
                    <div className="space-y-2">
                      {req.items.map((item, itemIdx) => (
                        <div key={itemIdx} className="flex items-center gap-2 text-sm">
                          <CheckCircle2 className="h-4 w-4 text-green-600 flex-shrink-0" />
                          {item}
                        </div>
                      ))}
                    </div>
                  </Card>
                ))}
              </div>
            </Card>
          </motion.div>
        </div>
      </section>

      {/* Global Cooperation Mechanisms */}
      <section className="py-20 px-6">
        <div className="container max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <Badge variant="secondary" className="text-sm mb-4">International Engagement</Badge>
            <h2 className="text-4xl font-bold mb-4">Global Cooperation Mechanisms</h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              TC260 Framework 2.0 introduces mechanisms for international cooperation on AI safety governance.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-6">
            {globalCooperationMechanisms.map((mechanism, idx) => (
              <motion.div
                key={mechanism.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.1 }}
              >
                <Card className="h-full p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="p-3 rounded-xl bg-green-500/10">
                      <mechanism.icon className="h-6 w-6 text-green-600" />
                    </div>
                    <h3 className="font-bold text-lg">{mechanism.title}</h3>
                  </div>
                  <p className="text-sm text-muted-foreground mb-4">{mechanism.description}</p>
                  <div className="space-y-2">
                    {mechanism.elements.map((element, elIdx) => (
                      <div key={elIdx} className="flex items-center gap-2 text-sm">
                        <CheckCircle2 className="h-4 w-4 text-green-600 flex-shrink-0" />
                        {element}
                      </div>
                    ))}
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How CSOAI Covers TC260 */}
      <section className="py-20 px-6 bg-muted/30">
        <div className="container max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <Badge className="text-sm mb-4 bg-green-500/10 text-green-600 border-green-500/30">
              Multi-Framework Support
            </Badge>
            <h2 className="text-4xl font-bold mb-4">How CSOAI Covers TC260</h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              Our platform provides comprehensive tools for TC260 compliance alongside EU and US frameworks.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {csoaiCoverage.map((feature, idx) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.05 }}
              >
                <Link href={feature.link}>
                  <Card className="h-full p-6 hover:shadow-lg transition-all hover:border-green-500/30 cursor-pointer group">
                    <h3 className="text-lg font-bold mb-2 group-hover:text-green-600 transition-colors">
                      {feature.title}
                    </h3>
                    <p className="text-sm text-muted-foreground mb-4">{feature.description}</p>
                    <div className="flex items-center text-green-600 text-sm font-medium">
                      Learn more
                      <ArrowRight className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" />
                    </div>
                  </Card>
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Training CTA */}
      <section className="py-20 px-6 bg-gradient-to-r from-red-600 to-orange-600 text-white">
        <div className="container max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center space-y-6"
          >
            <Badge variant="secondary" className="text-sm bg-white/20 text-white border-white/30">
              <Award className="h-4 w-4 mr-2" />
              Global AI Governance
            </Badge>
            <h2 className="text-4xl md:text-5xl font-bold">
              Master Multi-Framework Compliance
            </h2>
            <p className="text-xl text-red-100 max-w-3xl mx-auto">
              Our comprehensive training program covers TC260 alongside EU AI Act, NIST AI RMF, and ISO 42001.
              Build expertise in global AI governance and lead your organization's compliance efforts.
            </p>
            <div className="flex flex-wrap gap-4 justify-center pt-4">
              <Link href="/courses">
                <Button size="lg" variant="secondary" className="bg-white text-red-700 hover:bg-red-50">
                  <BookOpen className="mr-2 h-5 w-5" />
                  Browse Training Modules
                </Button>
              </Link>
              <Link href="/certification">
                <Button size="lg" variant="outline" className="border-white text-white hover:bg-white/10">
                  <Award className="mr-2 h-5 w-5" />
                  View Certifications
                </Button>
              </Link>
            </div>
            <div className="flex items-center justify-center gap-8 pt-6 text-red-100 flex-wrap">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="h-5 w-5" />
                <span>TC260 + EU + US Coverage</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="h-5 w-5" />
                <span>Practical Implementation</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="h-5 w-5" />
                <span>Global Best Practices</span>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-20 px-6">
        <div className="container max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <Badge variant="secondary" className="text-sm mb-4">Got Questions?</Badge>
            <h2 className="text-4xl font-bold mb-4">Frequently Asked Questions</h2>
            <p className="text-xl text-muted-foreground">
              Common questions about China's TC260 AI Safety Governance Framework.
            </p>
          </motion.div>

          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, idx) => (
              <AccordionItem key={idx} value={`item-${idx}`}>
                <AccordionTrigger className="text-left hover:no-underline">
                  <span className="font-semibold">{faq.question}</span>
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* Related Frameworks */}
      <section className="py-20 px-6 bg-muted/30">
        <div className="container max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl font-bold mb-4">Related Frameworks</h2>
            <p className="text-muted-foreground">
              Explore how other AI governance frameworks compare to TC260.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-6">
            <Link href="/guides/eu-ai-act">
              <Card className="p-6 hover:shadow-lg transition-shadow cursor-pointer">
                <div className="flex items-center gap-3 mb-3">
                  <div className="p-2 rounded-lg bg-blue-500/10">
                    <Globe className="h-6 w-6 text-blue-600" />
                  </div>
                  <h3 className="font-bold">EU AI Act</h3>
                </div>
                <p className="text-sm text-muted-foreground mb-4">
                  The EU's comprehensive AI regulation with binding requirements.
                </p>
                <span className="text-blue-600 text-sm font-medium flex items-center">
                  Read Guide <ArrowRight className="ml-2 h-4 w-4" />
                </span>
              </Card>
            </Link>
            <Link href="/guides/nist-ai-rmf">
              <Card className="p-6 hover:shadow-lg transition-shadow cursor-pointer">
                <div className="flex items-center gap-3 mb-3">
                  <div className="p-2 rounded-lg bg-blue-500/10">
                    <Building2 className="h-6 w-6 text-blue-600" />
                  </div>
                  <h3 className="font-bold">NIST AI RMF</h3>
                </div>
                <p className="text-sm text-muted-foreground mb-4">
                  The US voluntary framework for AI risk management.
                </p>
                <span className="text-blue-600 text-sm font-medium flex items-center">
                  Read Guide <ArrowRight className="ml-2 h-4 w-4" />
                </span>
              </Card>
            </Link>
            <Link href="/guides/iso-42001">
              <Card className="p-6 hover:shadow-lg transition-shadow cursor-pointer">
                <div className="flex items-center gap-3 mb-3">
                  <div className="p-2 rounded-lg bg-purple-500/10">
                    <Award className="h-6 w-6 text-purple-600" />
                  </div>
                  <h3 className="font-bold">ISO/IEC 42001</h3>
                </div>
                <p className="text-sm text-muted-foreground mb-4">
                  The certifiable international AI management system standard.
                </p>
                <span className="text-purple-600 text-sm font-medium flex items-center">
                  Read Guide <ArrowRight className="ml-2 h-4 w-4" />
                </span>
              </Card>
            </Link>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 px-6">
        <div className="container max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="space-y-6"
          >
            <h2 className="text-4xl font-bold">
              Ready for Global AI Compliance?
            </h2>
            <p className="text-xl text-muted-foreground">
              Navigate TC260, EU AI Act, NIST AI RMF, and ISO 42001 with a unified platform.
            </p>
            <div className="flex flex-wrap gap-4 justify-center">
              <Link href="/signup">
                <Button size="lg" className="bg-gradient-to-r from-red-600 to-orange-600 hover:from-red-700 hover:to-orange-700">
                  Start Free Trial
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
              </Link>
              <Link href="/enterprise">
                <Button size="lg" variant="outline">
                  Contact Enterprise Sales
                </Button>
              </Link>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
